[tool.poetry]
name = "utils"
version = "0.1.0"
description = "A collection of utilities used for data retreival."
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
